### PR TITLE
feat(config): add subscription id as a config property

### PR DESCRIPTION
**Pull request by coolguy1990**
See https://github.com/zalando-nakadi/fahrschein/issues/427

### CODE REVIEW

**Comment by otrosien** [comment]
@coolguy1990 this PR is stale for some time, and still marked as draft. Do you need support in getting it ready for reviewing?

**Comment by coolguy1990** [comment]
@otrosien sorry about the delay. the pull request is not ready for review.

**Comment by otrosien** [comment]
Thanks, can you reduce the change in the README to only the lines you're adding?

**Comment by otrosien** [comment]
I'll have to close and reopen your PR from this repository to enable Codacy integration.

**Comment by otrosien** [comment]
https://github.com/zalando-nakadi/fahrschein/pull/440

**Pull request closed without merging**
