### PR TITLE
removed false information from the doc

### PR DESCRIPTION
**Pull request by adyach**
removed false information from the doc

### CODE REVIEW

**Comment by ePaul** [comment]
:+1:

**Comment by adyach** [comment]
👍

**Comment by adyach** [comment]
`2023-10-05 08:39:24.821Z error [CodacyCoverageReporter] Invalid configuration: Empty argument for --project-token  - (CodacyCoverageReporter.scala:25)`

@otrosien could you help with the issue?

**Comment by otrosien** [comment]
codacy token is not available for PRs from forked repos (security).

**Pull request closed without merging**
