### PR TITLE
Small pgsql/redis cleanup

### PR DESCRIPTION
**Pull request by othon2000**
removing some leftovers after https://github.com/zalando-nakadi/fahrschein/pull/326

### CODE REVIEW

**Comment by othon2000** [comment]
:+1:

**Comment by otrosien** [comment]
Nakadi-Klients and Reactive-Nakadi are both dead for years, and I never even heard about straw. Let's scrap this table completely and recreate it with a comparison against nakadi-java maybe...

**Comment by otrosien** [comment]
👍

**Comment by othon2000** [comment]
:+1:

**Pull request merged**
