### PR TITLE
Micrometer Metrics

### PR DESCRIPTION
**Pull request by tobias-bahls**
* Ported the default `MetricsCollector` and `LastActivityMetricsCollector` to Micrometer for those on Spring Boot 2. 
* Moved `MultiplexingMetricsCollector` to the core module as it is independent of the metrics technology.
* Switched travis to `openjdk8` as `oraclejdk8` is not supported anymore

### CODE REVIEW

**Comment by whiskeysierra** [comment]
>     * Ported the default `MetricsCollector` and `LastActivityMetricsCollector` to Dropwizard for those on Spring Boot 2.

Meant to say Micrometer?

**Comment by jhorstmann** [comment]
I have no real way of testing this, but LGTM

**Comment by jhorstmann** [comment]
:+1:

**Comment by tobias-bahls** [comment]
@jhorstmann Do you need anything else to get this merged?

**Pull request closed without merging**
