### PR TITLE
declare EventPublishingException

### PR DESCRIPTION
**Pull request by othon2000**
declare EventPublishingException in NakadiClient.publish

https://github.com/zalando-nakadi/fahrschein/issues/270

### CODE REVIEW

**Comment by otrosien** [comment]
👍

**Comment by ePaul** [comment]
:+1:

**Comment by othon2000** [comment]
:+1:

**Comment by otrosien** [comment]
LGTM

**Comment by otrosien** [comment]
👍

**Comment by othon2000** [comment]
:+1:

**Comment by othon2000** [comment]
closing this PR to see if opening a new one fixes the problem with zappr not recognizing my approvals

**Pull request closed without merging**
